Разметил главную страницу
htmlacademy-htmlcss/1270227-technomart-29 pull request #2
Opened 2020-09-15 12:43 UTC by 333triblle

2020-09-15 14:30 UTC, Vallek requested changes
Привет! Со второй страницей поспешил немного:) Пока что не нужно это делать. Сначала лучше убедиться, что все верно на главной. А потом уже можно вторую.

В целом хорошо. Здорово, что уже семантику используешь, address. Ссылки в первом блоке по ТЗ.

2020-09-15 14:30 UTC, Vallek commented on index.html
> +        <li><a href="#">Кредит</a></li>
Не хватает карточки для кредита

2020-09-15 14:30 UTC, Vallek commented on index.html
> +          <section>
section это какая-то смысловая часть. Поэтому список тоже должен в нее входить. А для контактов дальше можно отдельную секцию тоже сделать. Но это не обязательно.

2020-09-15 14:30 UTC, Vallek commented on index.html
> +        <p>© 2010–2019 Компания «Техномарт»<br>
Символы типа копирайта нужно заменять html спецсимолами. Можно вот тут найти https://unicode-table.com/ru/

2020-09-16 08:30 UTC, 333triblle commented on index.html
> +        <li><a href="#">Кредит</a></li>
вот тут не понял, что нужно сделать

2020-09-16 09:04 UTC, 333triblle commented on index.html
> +        <li><a href="#">Кредит</a></li>
кажется не могу найти невидимые слои или pop up

2020-09-17 07:59 UTC, Vallek requested changes
Привет! 

1. Забыл переместить меню в шапку. Может пропустил коммент.
2. На странице каталога не хватает имени юзера.
3. Не хватает двух слайдов в первом слайдере на главной.

Я принял главную и отправил на доработку каталог, чтобы там не висело много доработок)

2020-09-17 08:07 UTC, merged